# Generated by Django 5.1.7 on 2025-03-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shortify', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URLShortener',
            new_name='URLMapping',
        ),
    ]
